/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RecipeId = IDL.Nat;
export const FlagId = IDL.Nat;
export const FlagStatus = IDL.Variant({
  'otvoreno' : IDL.Null,
  'rijeseno' : IDL.Null,
});
export const ImprovementFlag = IDL.Record({
  'id' : FlagId,
  'status' : FlagStatus,
  'recipeId' : RecipeId,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const NoteId = IDL.Nat;
export const CollabNote = IDL.Record({
  'id' : NoteId,
  'recipeId' : RecipeId,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
});
export const DietaryTag = IDL.Variant({
  'veganski' : IDL.Null,
  'bezGlutena' : IDL.Null,
  'vegetarijansko' : IDL.Null,
});
export const Cuisine = IDL.Variant({
  'hrvatska' : IDL.Null,
  'azijska' : IDL.Null,
  'francuska' : IDL.Null,
  'talijanska' : IDL.Null,
  'ostalo' : IDL.Null,
});
export const Category = IDL.Variant({
  'deserti' : IDL.Null,
  'glavnaJela' : IDL.Null,
  'pica' : IDL.Null,
  'predjela' : IDL.Null,
});
export const Ingredient = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'quantity' : IDL.Text,
});
export const RecipeInput = IDL.Record({
  'title' : IDL.Text,
  'cookTime' : IDL.Nat,
  'steps' : IDL.Vec(IDL.Text),
  'dietaryTags' : IDL.Vec(DietaryTag),
  'cuisine' : Cuisine,
  'prepTime' : IDL.Nat,
  'category' : Category,
  'servings' : IDL.Nat,
  'ingredients' : IDL.Vec(Ingredient),
});
export const Recipe = IDL.Record({
  'id' : RecipeId,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'cookTime' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'steps' : IDL.Vec(IDL.Text),
  'dietaryTags' : IDL.Vec(DietaryTag),
  'cuisine' : Cuisine,
  'prepTime' : IDL.Nat,
  'category' : Category,
  'servings' : IDL.Nat,
  'ingredients' : IDL.Vec(Ingredient),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addFlag' : IDL.Func([RecipeId, IDL.Text], [ImprovementFlag], []),
  'addNote' : IDL.Func([RecipeId, IDL.Text], [CollabNote], []),
  'createRecipe' : IDL.Func([RecipeInput], [Recipe], []),
  'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
  'deleteRecipe' : IDL.Func([RecipeId], [IDL.Bool], []),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getFlagsForRecipe' : IDL.Func(
      [RecipeId],
      [IDL.Vec(ImprovementFlag)],
      ['query'],
    ),
  'getNotesForRecipe' : IDL.Func([RecipeId], [IDL.Vec(CollabNote)], ['query']),
  'getRecipe' : IDL.Func([RecipeId], [IDL.Opt(Recipe)], ['query']),
  'resolveFlag' : IDL.Func([FlagId], [IDL.Bool], []),
  'suggestRecipes' : IDL.Func(
      [IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateRecipe' : IDL.Func([RecipeId, RecipeInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RecipeId = IDL.Nat;
  const FlagId = IDL.Nat;
  const FlagStatus = IDL.Variant({
    'otvoreno' : IDL.Null,
    'rijeseno' : IDL.Null,
  });
  const ImprovementFlag = IDL.Record({
    'id' : FlagId,
    'status' : FlagStatus,
    'recipeId' : RecipeId,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const NoteId = IDL.Nat;
  const CollabNote = IDL.Record({
    'id' : NoteId,
    'recipeId' : RecipeId,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
  });
  const DietaryTag = IDL.Variant({
    'veganski' : IDL.Null,
    'bezGlutena' : IDL.Null,
    'vegetarijansko' : IDL.Null,
  });
  const Cuisine = IDL.Variant({
    'hrvatska' : IDL.Null,
    'azijska' : IDL.Null,
    'francuska' : IDL.Null,
    'talijanska' : IDL.Null,
    'ostalo' : IDL.Null,
  });
  const Category = IDL.Variant({
    'deserti' : IDL.Null,
    'glavnaJela' : IDL.Null,
    'pica' : IDL.Null,
    'predjela' : IDL.Null,
  });
  const Ingredient = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'quantity' : IDL.Text,
  });
  const RecipeInput = IDL.Record({
    'title' : IDL.Text,
    'cookTime' : IDL.Nat,
    'steps' : IDL.Vec(IDL.Text),
    'dietaryTags' : IDL.Vec(DietaryTag),
    'cuisine' : Cuisine,
    'prepTime' : IDL.Nat,
    'category' : Category,
    'servings' : IDL.Nat,
    'ingredients' : IDL.Vec(Ingredient),
  });
  const Recipe = IDL.Record({
    'id' : RecipeId,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'cookTime' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'steps' : IDL.Vec(IDL.Text),
    'dietaryTags' : IDL.Vec(DietaryTag),
    'cuisine' : Cuisine,
    'prepTime' : IDL.Nat,
    'category' : Category,
    'servings' : IDL.Nat,
    'ingredients' : IDL.Vec(Ingredient),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addFlag' : IDL.Func([RecipeId, IDL.Text], [ImprovementFlag], []),
    'addNote' : IDL.Func([RecipeId, IDL.Text], [CollabNote], []),
    'createRecipe' : IDL.Func([RecipeInput], [Recipe], []),
    'deleteNote' : IDL.Func([NoteId], [IDL.Bool], []),
    'deleteRecipe' : IDL.Func([RecipeId], [IDL.Bool], []),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getFlagsForRecipe' : IDL.Func(
        [RecipeId],
        [IDL.Vec(ImprovementFlag)],
        ['query'],
      ),
    'getNotesForRecipe' : IDL.Func(
        [RecipeId],
        [IDL.Vec(CollabNote)],
        ['query'],
      ),
    'getRecipe' : IDL.Func([RecipeId], [IDL.Opt(Recipe)], ['query']),
    'resolveFlag' : IDL.Func([FlagId], [IDL.Bool], []),
    'suggestRecipes' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateRecipe' : IDL.Func([RecipeId, RecipeInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };