/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'deserti' : null } |
  { 'glavnaJela' : null } |
  { 'pica' : null } |
  { 'predjela' : null };
export interface CollabNote {
  'id' : NoteId,
  'recipeId' : RecipeId,
  'createdAt' : bigint,
  'text' : string,
}
export type Cuisine = { 'hrvatska' : null } |
  { 'azijska' : null } |
  { 'francuska' : null } |
  { 'talijanska' : null } |
  { 'ostalo' : null };
export type DietaryTag = { 'veganski' : null } |
  { 'bezGlutena' : null } |
  { 'vegetarijansko' : null };
export type FlagId = bigint;
export type FlagStatus = { 'otvoreno' : null } |
  { 'rijeseno' : null };
export interface ImprovementFlag {
  'id' : FlagId,
  'status' : FlagStatus,
  'recipeId' : RecipeId,
  'createdAt' : bigint,
  'description' : string,
}
export interface Ingredient {
  'name' : string,
  'unit' : string,
  'quantity' : string,
}
export type NoteId = bigint;
export interface Recipe {
  'id' : RecipeId,
  'title' : string,
  'createdAt' : bigint,
  'cookTime' : bigint,
  'updatedAt' : bigint,
  'steps' : Array<string>,
  'dietaryTags' : Array<DietaryTag>,
  'cuisine' : Cuisine,
  'prepTime' : bigint,
  'category' : Category,
  'servings' : bigint,
  'ingredients' : Array<Ingredient>,
}
export type RecipeId = bigint;
export interface RecipeInput {
  'title' : string,
  'cookTime' : bigint,
  'steps' : Array<string>,
  'dietaryTags' : Array<DietaryTag>,
  'cuisine' : Cuisine,
  'prepTime' : bigint,
  'category' : Category,
  'servings' : bigint,
  'ingredients' : Array<Ingredient>,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addFlag' : ActorMethod<[RecipeId, string], ImprovementFlag>,
  'addNote' : ActorMethod<[RecipeId, string], CollabNote>,
  'createRecipe' : ActorMethod<[RecipeInput], Recipe>,
  'deleteNote' : ActorMethod<[NoteId], boolean>,
  'deleteRecipe' : ActorMethod<[RecipeId], boolean>,
  'getAllRecipes' : ActorMethod<[], Array<Recipe>>,
  'getFlagsForRecipe' : ActorMethod<[RecipeId], Array<ImprovementFlag>>,
  'getNotesForRecipe' : ActorMethod<[RecipeId], Array<CollabNote>>,
  'getRecipe' : ActorMethod<[RecipeId], [] | [Recipe]>,
  'resolveFlag' : ActorMethod<[FlagId], boolean>,
  'suggestRecipes' : ActorMethod<[Array<string>, Array<string>], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateRecipe' : ActorMethod<[RecipeId, RecipeInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];