/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type NoteId = bigint;
export interface RecipeInput {
    title: string;
    cookTime: bigint;
    steps: Array<string>;
    dietaryTags: Array<DietaryTag>;
    cuisine: Cuisine;
    prepTime: bigint;
    category: Category;
    servings: bigint;
    ingredients: Array<Ingredient>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CollabNote {
    id: NoteId;
    recipeId: RecipeId;
    createdAt: bigint;
    text: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type RecipeId = bigint;
export type FlagId = bigint;
export interface Ingredient {
    name: string;
    unit: string;
    quantity: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ImprovementFlag {
    id: FlagId;
    status: FlagStatus;
    recipeId: RecipeId;
    createdAt: bigint;
    description: string;
}
export interface Recipe {
    id: RecipeId;
    title: string;
    createdAt: bigint;
    cookTime: bigint;
    updatedAt: bigint;
    steps: Array<string>;
    dietaryTags: Array<DietaryTag>;
    cuisine: Cuisine;
    prepTime: bigint;
    category: Category;
    servings: bigint;
    ingredients: Array<Ingredient>;
}
export enum Category {
    deserti = "deserti",
    glavnaJela = "glavnaJela",
    pica = "pica",
    predjela = "predjela"
}
export enum Cuisine {
    hrvatska = "hrvatska",
    azijska = "azijska",
    francuska = "francuska",
    talijanska = "talijanska",
    ostalo = "ostalo"
}
export enum DietaryTag {
    veganski = "veganski",
    bezGlutena = "bezGlutena",
    vegetarijansko = "vegetarijansko"
}
export enum FlagStatus {
    otvoreno = "otvoreno",
    rijeseno = "rijeseno"
}
export interface backendInterface {
    addFlag(recipeId: RecipeId, description: string): Promise<ImprovementFlag>;
    addNote(recipeId: RecipeId, text: string): Promise<CollabNote>;
    createRecipe(input: RecipeInput): Promise<Recipe>;
    deleteNote(noteId: NoteId): Promise<boolean>;
    deleteRecipe(id: RecipeId): Promise<boolean>;
    getAllRecipes(): Promise<Array<Recipe>>;
    getFlagsForRecipe(recipeId: RecipeId): Promise<Array<ImprovementFlag>>;
    getNotesForRecipe(recipeId: RecipeId): Promise<Array<CollabNote>>;
    getRecipe(id: RecipeId): Promise<Recipe | null>;
    resolveFlag(flagId: FlagId): Promise<boolean>;
    suggestRecipes(ingredients: Array<string>, dietaryRestrictions: Array<string>): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateRecipe(id: RecipeId, input: RecipeInput): Promise<boolean>;
}
import type { Category as _Category, Cuisine as _Cuisine, DietaryTag as _DietaryTag, FlagId as _FlagId, FlagStatus as _FlagStatus, ImprovementFlag as _ImprovementFlag, Ingredient as _Ingredient, Recipe as _Recipe, RecipeId as _RecipeId, RecipeInput as _RecipeInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFlag(arg0: RecipeId, arg1: string): Promise<ImprovementFlag> {
        if (this.processError) {
            try {
                const result = await this.actor.addFlag(arg0, arg1);
                return from_candid_ImprovementFlag_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFlag(arg0, arg1);
            return from_candid_ImprovementFlag_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addNote(arg0: RecipeId, arg1: string): Promise<CollabNote> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0, arg1);
            return result;
        }
    }
    async createRecipe(arg0: RecipeInput): Promise<Recipe> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecipe(to_candid_RecipeInput_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Recipe_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecipe(to_candid_RecipeInput_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Recipe_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNote(arg0: NoteId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteRecipe(arg0: RecipeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecipe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecipe(arg0);
            return result;
        }
    }
    async getAllRecipes(): Promise<Array<Recipe>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecipes();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecipes();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlagsForRecipe(arg0: RecipeId): Promise<Array<ImprovementFlag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlagsForRecipe(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlagsForRecipe(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesForRecipe(arg0: RecipeId): Promise<Array<CollabNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesForRecipe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesForRecipe(arg0);
            return result;
        }
    }
    async getRecipe(arg0: RecipeId): Promise<Recipe | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipe(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipe(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async resolveFlag(arg0: FlagId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveFlag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveFlag(arg0);
            return result;
        }
    }
    async suggestRecipes(arg0: Array<string>, arg1: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.suggestRecipes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suggestRecipes(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateRecipe(arg0: RecipeId, arg1: RecipeInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecipe(arg0, to_candid_RecipeInput_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecipe(arg0, to_candid_RecipeInput_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Category_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Cuisine_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cuisine): Cuisine {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_DietaryTag_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DietaryTag): DietaryTag {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_FlagStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlagStatus): FlagStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ImprovementFlag_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImprovementFlag): ImprovementFlag {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Recipe_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recipe): Recipe {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Recipe]): Recipe | null {
    return value.length === 0 ? null : from_candid_Recipe_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecipeId;
    title: string;
    createdAt: bigint;
    cookTime: bigint;
    updatedAt: bigint;
    steps: Array<string>;
    dietaryTags: Array<_DietaryTag>;
    cuisine: _Cuisine;
    prepTime: bigint;
    category: _Category;
    servings: bigint;
    ingredients: Array<_Ingredient>;
}): {
    id: RecipeId;
    title: string;
    createdAt: bigint;
    cookTime: bigint;
    updatedAt: bigint;
    steps: Array<string>;
    dietaryTags: Array<DietaryTag>;
    cuisine: Cuisine;
    prepTime: bigint;
    category: Category;
    servings: bigint;
    ingredients: Array<Ingredient>;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        cookTime: value.cookTime,
        updatedAt: value.updatedAt,
        steps: value.steps,
        dietaryTags: from_candid_vec_n16(_uploadFile, _downloadFile, value.dietaryTags),
        cuisine: from_candid_Cuisine_n19(_uploadFile, _downloadFile, value.cuisine),
        prepTime: value.prepTime,
        category: from_candid_Category_n21(_uploadFile, _downloadFile, value.category),
        servings: value.servings,
        ingredients: value.ingredients
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FlagId;
    status: _FlagStatus;
    recipeId: _RecipeId;
    createdAt: bigint;
    description: string;
}): {
    id: FlagId;
    status: FlagStatus;
    recipeId: RecipeId;
    createdAt: bigint;
    description: string;
} {
    return {
        id: value.id,
        status: from_candid_FlagStatus_n3(_uploadFile, _downloadFile, value.status),
        recipeId: value.recipeId,
        createdAt: value.createdAt,
        description: value.description
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    veganski: null;
} | {
    bezGlutena: null;
} | {
    vegetarijansko: null;
}): DietaryTag {
    return "veganski" in value ? DietaryTag.veganski : "bezGlutena" in value ? DietaryTag.bezGlutena : "vegetarijansko" in value ? DietaryTag.vegetarijansko : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hrvatska: null;
} | {
    azijska: null;
} | {
    francuska: null;
} | {
    talijanska: null;
} | {
    ostalo: null;
}): Cuisine {
    return "hrvatska" in value ? Cuisine.hrvatska : "azijska" in value ? Cuisine.azijska : "francuska" in value ? Cuisine.francuska : "talijanska" in value ? Cuisine.talijanska : "ostalo" in value ? Cuisine.ostalo : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deserti: null;
} | {
    glavnaJela: null;
} | {
    pica: null;
} | {
    predjela: null;
}): Category {
    return "deserti" in value ? Category.deserti : "glavnaJela" in value ? Category.glavnaJela : "pica" in value ? Category.pica : "predjela" in value ? Category.predjela : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    otvoreno: null;
} | {
    rijeseno: null;
}): FlagStatus {
    return "otvoreno" in value ? FlagStatus.otvoreno : "rijeseno" in value ? FlagStatus.rijeseno : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DietaryTag>): Array<DietaryTag> {
    return value.map((x)=>from_candid_DietaryTag_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recipe>): Array<Recipe> {
    return value.map((x)=>from_candid_Recipe_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImprovementFlag>): Array<ImprovementFlag> {
    return value.map((x)=>from_candid_ImprovementFlag_n1(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Cuisine_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cuisine): _Cuisine {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_DietaryTag_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryTag): _DietaryTag {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_RecipeInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecipeInput): _RecipeInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    cookTime: bigint;
    steps: Array<string>;
    dietaryTags: Array<DietaryTag>;
    cuisine: Cuisine;
    prepTime: bigint;
    category: Category;
    servings: bigint;
    ingredients: Array<Ingredient>;
}): {
    title: string;
    cookTime: bigint;
    steps: Array<string>;
    dietaryTags: Array<_DietaryTag>;
    cuisine: _Cuisine;
    prepTime: bigint;
    category: _Category;
    servings: bigint;
    ingredients: Array<_Ingredient>;
} {
    return {
        title: value.title,
        cookTime: value.cookTime,
        steps: value.steps,
        dietaryTags: to_candid_vec_n7(_uploadFile, _downloadFile, value.dietaryTags),
        cuisine: to_candid_Cuisine_n10(_uploadFile, _downloadFile, value.cuisine),
        prepTime: value.prepTime,
        category: to_candid_Category_n12(_uploadFile, _downloadFile, value.category),
        servings: value.servings,
        ingredients: value.ingredients
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cuisine): {
    hrvatska: null;
} | {
    azijska: null;
} | {
    francuska: null;
} | {
    talijanska: null;
} | {
    ostalo: null;
} {
    return value == Cuisine.hrvatska ? {
        hrvatska: null
    } : value == Cuisine.azijska ? {
        azijska: null
    } : value == Cuisine.francuska ? {
        francuska: null
    } : value == Cuisine.talijanska ? {
        talijanska: null
    } : value == Cuisine.ostalo ? {
        ostalo: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    deserti: null;
} | {
    glavnaJela: null;
} | {
    pica: null;
} | {
    predjela: null;
} {
    return value == Category.deserti ? {
        deserti: null
    } : value == Category.glavnaJela ? {
        glavnaJela: null
    } : value == Category.pica ? {
        pica: null
    } : value == Category.predjela ? {
        predjela: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DietaryTag): {
    veganski: null;
} | {
    bezGlutena: null;
} | {
    vegetarijansko: null;
} {
    return value == DietaryTag.veganski ? {
        veganski: null
    } : value == DietaryTag.bezGlutena ? {
        bezGlutena: null
    } : value == DietaryTag.vegetarijansko ? {
        vegetarijansko: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DietaryTag>): Array<_DietaryTag> {
    return value.map((x)=>to_candid_DietaryTag_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
